theme: jekyll-theme-cayman
title: "Ruocheng Zhai 翟若成"
description: "Graduate Student at the Department of Astronomy & Astrophysics, Penn State"
logo: DSC_0590.jpg
show_downloads: false

# Navigation links
nav:
  - title: "About"
    url: /
  - title: "Publications"
    url: /publications
  - title: "Research"
    url: /research
  - title: "CV"
    url: /cv
